# Generated by Django 2.1.4 on 2018-12-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
